### ISSUE TITLE
clean task in grunt production

### ISSUE THREAD

**Issue by markusfalk** [markusfalk/generator-kickstart#138]
all clean tasks get executed when running grunt production

**Comment by letsiz** [comment]
grunt.registerTask('default', [
    'clean:build',
    'replace',
    'imagemin',
    'sync',
    'compass:development',
    'requirejs:development',
    'uglify:deferred_development',
    'uglify:external',
    'modernizr'
  ]);

  grunt.registerTask('production', [
    'clean:build',
    'replace',
    'imagemin',
    'sync',
    'compass:production',
    'requirejs:production',
    'uglify:deferred_production',
    'uglify:external',
    'modernizr'
   ]);

  grunt.registerTask('test', [
    'csslint',
    'jshint',
    'accessibility',
    'connect',
    'qunit:all'
  ]);

  grunt.registerTask('doc', [
    'jsdoc'
  ]);
