### ISSUE TITLE
executing grunt causes an imagemin error

### ISSUE THREAD

**Issue by DeathAngelDaemon** [markusfalk/generator-kickstart#149]
I made the following steps:

1. setting up a whole new project with `yo kickstart`
2. everything went fine and the commands `npm install & bower install` were executed
3. after that was finished I wanted to execute `grunt` the first time, which ends in the following error

```
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'imagemin-jpegtran'
Warning: Task "imagemin" not found. Use --force to continue.

Aborted due to warnings.
```

I thought I can pass on the imagemin task and used `grunt --force`. But that doesn't work either.

```
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'imagemin-jpegtran'
Warning: Task "imagemin" not found. Used --force, continuing.

Done, but with warnings.
```

And **no** `build` folder was created.

**Comment by markusfalk** [comment]
This is something I have heard from a view windows users. Try to install the imagemin-task again. After that it usally works fine.

```javascript
npm i grunt-contrib-imagemin
```
