### ISSUE TITLE
distinguish two different cases in one app

### ISSUE THREAD

**Issue by DeathAngelDaemon** [markusfalk/generator-kickstart#91]
If possible, it would be nice to handle two cases in one app.

Let's say I have a component like "header" which is responsible for the header-image with text on it.
On the startpage I have a bigger header than on any other page. At the moment I can only create a new component, like "header-start", which does nearly the same just the background-image is some pixel higher. That's silly, because both pages need and have the component "header".

So it would be great if I can use two (or more) html-files in one app:
* component "header" has two html-files: _"header.html"_ (which is for every page, except the startpage) and _"header-start.html"_ (which is only for the startpage)
* in my index.html I would like to use __{app:{header/header-start}}__ or __{app:{header}{header-start}}__ or something else, to call just the html-file for the startpage, which uses the same scss-file like the _header.html_

Maybe it sounds confusing and it not supports the intention of this generator, but it would clean up my list of components and make it more clearer. And for me it sounds more logical, then using two components.

**Comment by markusfalk** [comment]
```html
{app:{search:{search_alt}}}
```

```javascript
replace: {
      modules: {
        options: {
          excludeBuiltins: true,
          patterns: [
            {
              match: /{app:{(.+):{(.+)}}/g,
              replacement: function (match, placeholder, alternative) {
                return grunt.file.read('components/app/' + placeholder + '/' + alternative + '.html');
              }
            },
            {
              match: /{deferred:{(.+):{(.+)}}/g,
              replacement: function (match, placeholder, alternative) {
                return grunt.file.read('components/app/' + placeholder + '/' + alternative + '.html');
              }
            },
            {
              match: /{app:{[a-z|0-9|-]*}}/g,
              replacement: function (match, placeholder) {
                return grunt.file.read('components/app/' + placeholder + '/' + placeholder + '.html');
              }
            },
            {
              match: /{deferred:{[a-z|0-9|-]*}}/g,
              replacement: function (match, placeholder) {
                return grunt.file.read('components/app/_deferred/' + placeholder + '/' + placeholder + '.html');
              }
            }
          ]
        },
        files: [
          {
            expand: true,
            flatten: true,
            src: ['*.html'],
            dest: 'build/'
          }
        ]
      }
    },
```

**Comment by markusfalk** [comment]
might need to constrain component names to [a-z|0-9|-]

**Comment by DeathAngelDaemon** [comment]
:+1: good to see you've got this working.
I've no problem with such a constraint.

Thanks! That will make some things a bit easier. ;)

**Comment by markusfalk** [comment]
put app and deferred into one regex?

```javascript
// alternate html file
{(app|deferred):{(.+):{(.+)}}}

// and

// regular
{(app|deferred):{([a-z|0-9|-]*)}}
```

needs testing but would improve performance

**Comment by DeathAngelDaemon** [comment]
looks good.
and you might want to use `([\w\-]+)` for matching the strings
`\w` is equal to `[a-zA-Z0-9_]` and `\-` includes the dash
